default_install_hook_types: [pre-commit, pre-push]
default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=lf']

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: ['--py38-plus']

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies:
    - darglint
    - dlint
    - flake8
    - flake8-alfred
    - flake8-annotations-complexity
    - flake8-bandit
    - flake8-black
    - flake8-broken-line
    - flake8-bugbear
    - flake8-builtins
    - flake8-class-attributes-order
    - flake8-cognitive-complexity
    - flake8-comprehensions
    - flake8-debugger
    - flake8-docstrings
    - flake8-eradicate
    - flake8-executable
    - flake8-expression-complexity
    - flake8-functions
    - flake8-fixme
    - flake8-isort
    - flake8-logging-format
    - flake8-pep3101
    - flake8-print
    - flake8-pytest
    - flake8-pytest-style
    - flake8-requirements
    - flake8-rst
    - flake8-spellcheck
    - flake8-string-format
    - pep8-naming
    stages: [push]

- repo: local
  hooks:
  - id: tests
    name: run python tests
    entry: tox -q -e test
    language: system
    pass_filenames: false
    stages: [push]
    types: [python]
